### ISSUE TITLE
Running the container with bind mounts or volumes?

### ISSUE THREAD

**Issue by bluepuma77** [yunussandikci/docker-wordpress-sqlite#1]
Running the container as mentioned in "Usage"
```
docker run -d -p 8080:80 ghcr.io/yunussandikci/wordpress-sqlite:6.7.2-php8.3-apache
```
makes it hard to upgrade to a new Docker image, as the sqlite database and uploads (images, themes, plugins) will be lost.

Wouldn't it make more sense to use bind mounts or volumes to preserve files, like in [Docker Wordpress doc](https://hub.docker.com/_/wordpress)?
```
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html
```

Where is the SQLite database located?
